[versions]
appProjectPath = ":app"
dataProjectPath = ":data"
domainProjectPath = ":domain"
coreProjectPath = ":core"
coreuiProjectPath = ":core-ui"
featureMainProjectPath = ":feature:main"
appNamespace = "kg.geekstudio.kitsu"
